Sprint 3
ManukMamyan/middle.messenger.praktikum.yandex pull request #3
Opened 2023-01-21 17:24 UTC by ManukMamyan

Added routing, global store, chat api

2023-01-29 13:25 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу, есть некоторые замечания:
1. По заданию нельзя использовать fetch, axios и т.п., запросы к API должны быть реализованы через [XMLHttpRequest](https://learn.javascript.ru/ajax-xmlhttprequest)
2. Есть ошибки типизации и линтера
3. При переходе на страницу авторизации page not found на нетлифай, необходимо добавить [redirects в netlify.toml](https://docs.netlify.com/routing/redirects/)
4. Сообщения в чате не отправляются
5. Не получается сменить аватар

2023-01-29 13:25 UTC, podlovchenko commented on src/core/Block.ts
> +  _checkInDom() {
Для приватных методов не хватает модификатора private

2023-04-17 09:08 UTC, podlovchenko commented
Привет, в целом все хорошо
Осталось пару моментов
- Замечание по поводу нетлифае осталось актуальным
- Не подгружаются аватарки в чатах
<img width="322" alt="Снимок экрана 2023-04-17 в 12 06 14" src="https://user-images.githubusercontent.com/22602747/232438811-9b45626e-2092-42f1-995f-0d4773066099.png">

2023-04-17 18:04 UTC, ManukMamyan commented
Привет!
По поводу нетлифае - я добавлял в toml редирект - что то еще нужно было сделать?
По аватару чата поправил

2023-04-18 10:18 UTC, podlovchenko commented
Надо задеплоить из этой ветки, пока проблема есть

2023-04-23 13:49 UTC, ManukMamyan commented
> Надо задеплоить из этой ветки, пока проблема есть

Смержил Sprint_3 в ветку deploy - вроде все работает - https://rad-gecko-9fdf45.netlify.app/

Если что то упустил - просьба написать, что именно

2023-04-24 09:12 UTC, podlovchenko commented
Сейчас все ок, работу принимаю)

2023-05-10 16:13 UTC, merged